global using BuildingBlocks.Exceptions;
global using Carter;
global using HealthChecks.UI.Client;
global using Mapster;
global using Mediator;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using System.Text.Json.Serialization;
global using UserContent.API;
global using UserContent.API.Constants;
