// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserContent.Infrastructure.Data;

#nullable disable

namespace UserContent.Infrastructure.Migrations
{
    [DbContext(typeof(UserContentContext))]
    [Migration("20260423192127_AddReplyToComment")]
    partial class AddReplyToComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserContent.Domain.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("BandIds")
                        .HasColumnType("text")
                        .HasColumnName("band_ids");

                    b.Property<string>("BandNames")
                        .HasColumnType("text")
                        .HasColumnName("band_names");

                    b.Property<string>("BandSlugs")
                        .HasColumnType("text")
                        .HasColumnName("band_slugs");

                    b.Property<string>("CountryCodes")
                        .HasColumnType("text")
                        .HasColumnName("country_codes");

                    b.Property<string>("CountryNames")
                        .HasColumnType("text")
                        .HasColumnName("country_names");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<bool>("IsExplicit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_explicit");

                    b.Property<string>("PrimaryGenreName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_genre_name");

                    b.Property<string>("PrimaryGenreSlug")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("primary_genre_slug");

                    b.Property<int>("RatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("ratings_count");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.AlbumComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid?>("ReplyToCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_comment_id");

                    b.Property<string>("ReplyToUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reply_to_username");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("album_comments", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.AlbumReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("album_reviews", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.Band", b =>
                {
                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("band_name");

                    b.Property<string>("CountryCodes")
                        .HasColumnType("text")
                        .HasColumnName("country_codes");

                    b.Property<string>("CountryNames")
                        .HasColumnType("text")
                        .HasColumnName("country_names");

                    b.Property<int?>("DisbandedYear")
                        .HasColumnType("integer")
                        .HasColumnName("disbanded_year");

                    b.Property<int?>("FormedYear")
                        .HasColumnType("integer")
                        .HasColumnName("formed_year");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("PrimaryGenreName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_genre_name");

                    b.Property<string>("PrimaryGenreSlug")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("primary_genre_slug");

                    b.Property<int>("RatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("ratings_count");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("BandId");

                    b.ToTable("bands", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.BandComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid?>("ReplyToCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_comment_id");

                    b.Property<string>("ReplyToUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reply_to_username");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("band_comments", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.BandReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("band_reviews", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.CollectionAlbum", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.HasKey("CollectionId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("collection_albums", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.CollectionBand", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.HasKey("CollectionId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("collection_bands", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteAlbum", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<string>("UserReview")
                        .HasColumnType("text")
                        .HasColumnName("user_review");

                    b.HasKey("UserId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("favorite_albums", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteBand", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<bool>("IsFollowing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_following");

                    b.HasKey("UserId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("favorite_bands", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.UserProfileInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_date");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.AlbumComment", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Album", "Album")
                        .WithMany("Comments")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.AlbumComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Album");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("UserContent.Domain.Models.AlbumReview", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Album", "Album")
                        .WithMany("Reviews")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("UserContent.Domain.Models.BandComment", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Band", "Band")
                        .WithMany("Comments")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.BandComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Band");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("UserContent.Domain.Models.BandReview", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Band", "Band")
                        .WithMany("Reviews")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Collection", b =>
                {
                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.CollectionAlbum", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Album", "Album")
                        .WithMany("CollectionAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.Collection", "Collection")
                        .WithMany("CollectionAlbums")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("UserContent.Domain.Models.CollectionBand", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Band", "Band")
                        .WithMany("CollectionBands")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.Collection", "Collection")
                        .WithMany("CollectionBands")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteAlbum", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Album", "Album")
                        .WithMany("FavoriteAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("FavoriteAlbums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteBand", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Band", "Band")
                        .WithMany("FavoriteBands")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("FavoriteBands")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Album", b =>
                {
                    b.Navigation("CollectionAlbums");

                    b.Navigation("Comments");

                    b.Navigation("FavoriteAlbums");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("UserContent.Domain.Models.AlbumComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Band", b =>
                {
                    b.Navigation("CollectionBands");

                    b.Navigation("Comments");

                    b.Navigation("FavoriteBands");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("UserContent.Domain.Models.BandComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Collection", b =>
                {
                    b.Navigation("CollectionAlbums");

                    b.Navigation("CollectionBands");
                });

            modelBuilder.Entity("UserContent.Domain.Models.UserProfileInfo", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("FavoriteAlbums");

                    b.Navigation("FavoriteBands");
                });
#pragma warning restore 612, 618
        }
    }
}
