// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserContent.Infrastructure.Data;

#nullable disable

namespace UserContent.Infrastructure.Migrations
{
    [DbContext(typeof(UserContentContext))]
    [Migration("20260212134233_InitialCreateWithSeed")]
    partial class InitialCreateWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserContent.Domain.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.Band", b =>
                {
                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("band_name");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.HasKey("BandId");

                    b.ToTable("bands", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteAlbum", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<int?>("UserRating")
                        .HasColumnType("integer")
                        .HasColumnName("user_rating");

                    b.Property<string>("UserReview")
                        .HasColumnType("text")
                        .HasColumnName("user_review");

                    b.HasKey("UserId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("favorite_albums", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteBand", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<bool>("IsFollowing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_following");

                    b.HasKey("UserId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("favorite_bands", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.UserProfileInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_date");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteAlbum", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Album", "Album")
                        .WithMany("FavoriteAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("FavoriteAlbums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteBand", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Band", "Band")
                        .WithMany("FavoriteBands")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("FavoriteBands")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Album", b =>
                {
                    b.Navigation("FavoriteAlbums");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Band", b =>
                {
                    b.Navigation("FavoriteBands");
                });

            modelBuilder.Entity("UserContent.Domain.Models.UserProfileInfo", b =>
                {
                    b.Navigation("FavoriteAlbums");

                    b.Navigation("FavoriteBands");
                });
#pragma warning restore 612, 618
        }
    }
}
