// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserContent.Infrastructure.Data;

#nullable disable

namespace UserContent.Infrastructure.Migrations
{
    [DbContext(typeof(UserContentContext))]
    [Migration("20260416213607_RemoveUserRatingFromFavoriteAlbum")]
    partial class RemoveUserRatingFromFavoriteAlbum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserContent.Domain.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("BandNames")
                        .HasColumnType("text")
                        .HasColumnName("band_names");

                    b.Property<string>("BandSlugs")
                        .HasColumnType("text")
                        .HasColumnName("band_slugs");

                    b.Property<string>("CountryCodes")
                        .HasColumnType("text")
                        .HasColumnName("country_codes");

                    b.Property<string>("CountryNames")
                        .HasColumnType("text")
                        .HasColumnName("country_names");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("PrimaryGenreName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_genre_name");

                    b.Property<string>("PrimaryGenreSlug")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("primary_genre_slug");

                    b.Property<int>("RatingsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ratings_count");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.AlbumRating", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("UserId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("album_ratings", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.Band", b =>
                {
                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("band_name");

                    b.Property<string>("CountryCodes")
                        .HasColumnType("text")
                        .HasColumnName("country_codes");

                    b.Property<string>("CountryNames")
                        .HasColumnType("text")
                        .HasColumnName("country_names");

                    b.Property<int?>("DisbandedYear")
                        .HasColumnType("integer")
                        .HasColumnName("disbanded_year");

                    b.Property<int?>("FormedYear")
                        .HasColumnType("integer")
                        .HasColumnName("formed_year");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("PrimaryGenreName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_genre_name");

                    b.Property<string>("PrimaryGenreSlug")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("primary_genre_slug");

                    b.Property<int>("RatingsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ratings_count");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("BandId");

                    b.ToTable("bands", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.BandRating", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("UserId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("band_ratings", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteAlbum", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<string>("UserReview")
                        .HasColumnType("text")
                        .HasColumnName("user_review");

                    b.HasKey("UserId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("favorite_albums", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteBand", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<bool>("IsFollowing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_following");

                    b.HasKey("UserId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("favorite_bands", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.UserProfileInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_date");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("UserContent.Domain.Models.AlbumRating", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Album", "Album")
                        .WithMany("Ratings")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("AlbumRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.BandRating", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Band", "Band")
                        .WithMany("Ratings")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("BandRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteAlbum", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Album", "Album")
                        .WithMany("FavoriteAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("FavoriteAlbums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.FavoriteBand", b =>
                {
                    b.HasOne("UserContent.Domain.Models.Band", "Band")
                        .WithMany("FavoriteBands")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserContent.Domain.Models.UserProfileInfo", "User")
                        .WithMany("FavoriteBands")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Album", b =>
                {
                    b.Navigation("FavoriteAlbums");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("UserContent.Domain.Models.Band", b =>
                {
                    b.Navigation("FavoriteBands");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("UserContent.Domain.Models.UserProfileInfo", b =>
                {
                    b.Navigation("AlbumRatings");

                    b.Navigation("BandRatings");

                    b.Navigation("FavoriteAlbums");

                    b.Navigation("FavoriteBands");
                });
#pragma warning restore 612, 618
        }
    }
}
