global using System.Reflection;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Messaging.MassTransit;
global using Mapster;
global using MassTransit;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using UserContent.Application.Dtos;
global using UserContent.Domain.Models;