services:
  librarydb:
    image: postgres:16

  usercontentdb:
    image: postgres:16

  messagebroker:
    image: rabbitmq:management

  distributedcache:
    image: redis:7.2

  usercontent.api:
    image: ${DOCKER_REGISTRY-}usercontentapi
    build:
      context: .
      dockerfile: Services/UserContent/UserContent.API/Dockerfile

  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Services/Library/Library.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  blackenddeath.ui:
    image: ${DOCKER_REGISTRY-}blackenddeathui
    build:
      context: ../../blackenddeath.UI/blackanddeath.UI
      dockerfile: Dockerfile

volumes:
  postgres_library:
  postgres_usercontent:
  rabbitmq_data:
