services:
  librarydb:
    image: postgres:16

  usercontentdb:
    image: postgres:16
    
  identitydb:
    image: postgres:16

  messagebroker:
    image: rabbitmq:management

  distributedcache:
    image: redis:7.2

  activitydb:
    image: mongo:7

  mongo-express:
    image: mongo-express

  notificationsdb:
    image: postgres:16

  activity.api:
    image: ${DOCKER_REGISTRY-}activityapi
    build:
      context: .
      dockerfile: Services/Activity/Activity.API/Dockerfile

  notifications.api:
    image: ${DOCKER_REGISTRY-}notificationsapi
    build:
      context: .
      dockerfile: Services/Notifications/Notifications.API/Dockerfile

  usercontent.api:
    image: ${DOCKER_REGISTRY-}usercontentapi
    build:
      context: .
      dockerfile: Services/UserContent/UserContent.API/Dockerfile

  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Services/Library/Library.API/Dockerfile
    environment:
      - ConnectionStrings__Redis=distributedcache:6379

  identity.server:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/Identity/IdentityServer/Dockerfile

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  blackenddeath.ui:
    image: ${DOCKER_REGISTRY-}blackenddeathui
    build:
      context: ../../blackenddeath.UI/blackanddeath.UI
      dockerfile: Dockerfile

volumes:
  mongo_activity:
  postgres_library:
  postgres_usercontent:
  postgres_notifications:
  postgres_identity:
  rabbitmq_data:
  identity_dataprotection:
  seq_data:
