services:
  archivedb:
    image: postgres:16

  archive.api:
    image: ${DOCKER_REGISTRY-}archiveapi
    build:
      context: .
      dockerfile: Services/Archive/Archive.API/Dockerfile

volumes:
  postgres_archive:
