// <auto-generated />
using System;
using Archive.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Archive.API.Migrations
{
    [DbContext(typeof(ArchiveContext))]
    [Migration("20260127014042_InitialCreateWithSeed")]
    partial class InitialCreateWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Archive.API.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Format = 0,
                            Label = "Peaceville Records",
                            ReleaseDate = 1994,
                            Title = "Transilvanian Hunger",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Format = 0,
                            Label = "Misanthropy Records",
                            ReleaseDate = 1996,
                            Title = "Filosofem",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Format = 0,
                            Label = "Candlelight Records",
                            ReleaseDate = 1994,
                            Title = "In the Nightside Eclipse",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Format = 0,
                            Label = "Deathlike Silence Productions",
                            ReleaseDate = 1994,
                            Title = "De Mysteriis Dom Sathanas",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Format = 0,
                            Label = "Nuclear Blast",
                            ReleaseDate = 1995,
                            Title = "Storm of the Light's Bane",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Format = 0,
                            Label = "Nuclear Blast",
                            ReleaseDate = 2014,
                            Title = "The Satanist",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Archive.API.Models.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<int?>("DisbandedYear")
                        .HasColumnType("integer")
                        .HasColumnName("disbanded_year");

                    b.Property<int?>("FormedYear")
                        .HasColumnType("integer")
                        .HasColumnName("formed_year");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("bands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Bio = "Norwegian black metal band formed in 1986.",
                            CountryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            FormedYear = 1986,
                            Name = "Darkthrone",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Bio = "Norwegian black metal solo project by Varg Vikernes.",
                            CountryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            FormedYear = 1991,
                            Name = "Burzum",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Bio = "Norwegian black metal band, pioneers of symphonic black metal.",
                            CountryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            DisbandedYear = 2001,
                            FormedYear = 1991,
                            Name = "Emperor",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Bio = "Norwegian black metal band, one of the genre's founders.",
                            CountryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            FormedYear = 1984,
                            Name = "Mayhem",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Bio = "Swedish melodic black/death metal band.",
                            CountryId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            DisbandedYear = 2006,
                            FormedYear = 1989,
                            Name = "Dissection",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Bio = "Polish blackened death metal band.",
                            CountryId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            FormedYear = 1991,
                            Name = "Behemoth",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Archive.API.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            Code = "FR",
                            Name = "France"
                        });
                });

            modelBuilder.Entity("Archive.API.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_genre_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Metal"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Black Metal",
                            ParentGenreId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Death Metal",
                            ParentGenreId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "Doom Metal",
                            ParentGenreId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Name = "Thrash Metal",
                            ParentGenreId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Name = "Raw Black Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Name = "Melodic Black Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "Atmospheric Black Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Name = "Symphonic Black Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Name = "Depressive Black Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Name = "Melodic Death Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Name = "Technical Death Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Name = "Brutal Death Metal",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Name = "Funeral Doom",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("3000000a-0000-0000-0000-000000000000"),
                            Name = "Stoner Doom",
                            ParentGenreId = new Guid("20000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumBand", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("AlbumId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("album_bands", (string)null);
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumCountry", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.HasKey("AlbumId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("album_countries", (string)null);
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumGenre", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("AlbumId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("album_genres", (string)null);
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumTrack", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("AlbumId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("album_tracks", (string)null);
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.BandGenre", b =>
                {
                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid")
                        .HasColumnName("band_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("BandId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("band_genres", (string)null);
                });

            modelBuilder.Entity("Archive.API.Models.StreamingLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("embed_code");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasColumnName("platform");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("streaming_links", (string)null);
                });

            modelBuilder.Entity("Archive.API.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("tracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Title = "Transilvanian Hunger"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Title = "Over Fjell og Gjennom Torner"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Title = "Skald av Satans Sol"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Title = "Slottet i Det Fjerne"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Title = "Dunkelheit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Title = "Jesus' Tod"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Title = "Erblicket die Töchter des Firmaments"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Title = "Into the Infinity of Thoughts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Title = "The Burning Shadows of Silence"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0002-000000000000"),
                            Title = "Cosmic Keys to My Creations & Times"
                        });
                });

            modelBuilder.Entity("Archive.API.Models.Band", b =>
                {
                    b.HasOne("Archive.API.Models.Country", "Country")
                        .WithMany("Bands")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Archive.API.Models.Genre", b =>
                {
                    b.HasOne("Archive.API.Models.Genre", "ParentGenre")
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumBand", b =>
                {
                    b.HasOne("Archive.API.Models.Album", "Album")
                        .WithMany("Bands")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive.API.Models.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Band");
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumCountry", b =>
                {
                    b.HasOne("Archive.API.Models.Album", "Album")
                        .WithMany("Countries")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive.API.Models.Country", "Country")
                        .WithMany("Albums")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumGenre", b =>
                {
                    b.HasOne("Archive.API.Models.Album", "Album")
                        .WithMany("Genres")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive.API.Models.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.AlbumTrack", b =>
                {
                    b.HasOne("Archive.API.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive.API.Models.Track", "Track")
                        .WithMany("Albums")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Archive.API.Models.JoinTables.BandGenre", b =>
                {
                    b.HasOne("Archive.API.Models.Band", "Band")
                        .WithMany("Genres")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive.API.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Archive.API.Models.StreamingLink", b =>
                {
                    b.HasOne("Archive.API.Models.Album", "Album")
                        .WithMany("StreamingLinks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Archive.API.Models.Album", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("Countries");

                    b.Navigation("Genres");

                    b.Navigation("StreamingLinks");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Archive.API.Models.Band", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Archive.API.Models.Country", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Bands");
                });

            modelBuilder.Entity("Archive.API.Models.Genre", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("Archive.API.Models.Track", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
