// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserContent.API.Data;

#nullable disable

namespace UserContent.API.Migrations
{
    [DbContext(typeof(UserContentContext))]
    partial class UserContentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserContent.API.Models.FavoriteAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserProfileInfoUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UserRating")
                        .HasColumnType("integer");

                    b.Property<string>("UserReview")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileInfoUserId");

                    b.HasIndex("UserId", "AlbumId")
                        .IsUnique();

                    b.ToTable("FavoriteAlbums");
                });

            modelBuilder.Entity("UserContent.API.Models.FavoriteBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFollowing")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserProfileInfoUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileInfoUserId");

                    b.HasIndex("UserId", "BandId")
                        .IsUnique();

                    b.ToTable("FavoriteBands");
                });

            modelBuilder.Entity("UserContent.API.Models.UserProfileInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FavoriteAlbumsCount")
                        .HasColumnType("integer");

                    b.Property<int>("FavoriteBandsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("UserContent.API.Models.FavoriteAlbum", b =>
                {
                    b.HasOne("UserContent.API.Models.UserProfileInfo", null)
                        .WithMany("FavoriteAlbums")
                        .HasForeignKey("UserProfileInfoUserId");
                });

            modelBuilder.Entity("UserContent.API.Models.FavoriteBand", b =>
                {
                    b.HasOne("UserContent.API.Models.UserProfileInfo", null)
                        .WithMany("FavoriteBands")
                        .HasForeignKey("UserProfileInfoUserId");
                });

            modelBuilder.Entity("UserContent.API.Models.UserProfileInfo", b =>
                {
                    b.Navigation("FavoriteAlbums");

                    b.Navigation("FavoriteBands");
                });
#pragma warning restore 612, 618
        }
    }
}
